server:
  port: 8001

spring:
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    useSSL: false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      useSSL: false
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
